rem ˆê——
db2 LIST DATABASE DIRECTORY ON C:

rem ÄÝ’è
rem db2 CATALOG DATABASE MYDB ON C:

rem íœ
rem db2 DROP DATABASE MYDB

rem ì¬
db2 CREATE DATABASE MYDB ON C: USING CODESET UTF-8 TERRITORY JP COLLATE USING IDENTITY
